name: Continuous Integration
on:
  - pull_request
  - push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-version:
          - 4.09.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup OCaml v${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      # Generate the static site
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Clean Public Directory
        run: rm -rf doc/public
      - name: Install NPM Dependencies
        run: npm install -D postcss postcss-cli autoprefixer
      - name: Generate Static Site
        run: hugo -s doc -b https://watersofoblivion.github.io/nile -t docsy --minify --log

      # Build the compiler
      - name: Pin OPAM
        run: opam pin add nile.dev . --no-action
      - name: Install System Dependencies
        run: opam depext nile --yes --with-doc -with-test
      - name: Install OPAM Dependencies
        run: opam install . --deps-only --with-doc --with-test
      - name: Build Nile
        run: opam exec -- dune build bin

      # Run unit tests and generate coverage information
      - name: Run Unit Tests
        run: opam exec -- dune runtest test/unit --instrument-with bisect_ppx --force
      - name: Generate Unit Test Coverage Report
        run: opam exec -- bisect-ppx-report html -o ./doc/public/static/coverage/unit

      # Run integrations tests and generate coverage information
      - name: Run Integration Tests
        run: opam exec -- dune runtest test/integration --instrument-with bisect_ppx --force
      - name: Generate Integration Test Coverage Report
        run: opam exec -- bisect-ppx-report html -o ./doc/public/static/coverage/integration

      # Build the docs (TODO)
      - name: Build ODoc
        run: opam exec -- dune build @doc
      - name: Copy ODoc to Static Site
        run: cp -r ./_build/default/_doc/_html/* ./doc/public/static/odoc/

      - name: Deploy Static Site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          public_dir: ./doc/public
