name: Continuous Integration
on:
  - pull_request
  - push
jobs:
  # Build and test the commit
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Build and Test on ${{ matrix.os }}
    steps:
      # Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up OCaml
      - name: Setup OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.09.0

      # Build the compiler
      - name: Pin OPAM
        run: opam pin add nile.dev . --no-action
      - name: Install System Dependencies
        run: opam depext nile --yes --with-doc --with-test
      - name: Install OPAM Dependencies
        run: opam install . --deps-only --with-doc --with-test
      - name: Build Nile
        run: opam exec -- dune build bin

      # Run unit and integration tests
      - name: Run Unit Tests
        run: opam exec -- dune runtest test/unit --instrument-with bisect_ppx --force
      - name: Run Integration Tests
        run: opam exec -- dune runtest test/integration --instrument-with bisect_ppx --force

      # "Install" the executable
      - name: Install
        run: opam exec -- dune build @install

  # Generate the static documentation site
  generate-docs:
    name: Generate GitHub Pages Site
    if: github.ref == 'master'
    runs-on:
      - ubuntu-latest
    needs:
      - build-and-test
    steps:
      # Generate the static site
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Clean Public Directory
        run: rm -rf doc/public
      - name: Install NPM Dependencies
        run: npm install -D postcss postcss-cli autoprefixer
      - name: Generate Static Site
        run: hugo -s doc -b https://watersofoblivion.github.io/nile -t docsy --minify --log

      # Build the docs (TODO)
      - name: Build ODoc
        run: opam exec -- dune build @doc
      - name: Copy ODoc to Static Site
        run: cp -r ./_build/default/_doc/_html/* ./doc/public/static/odoc/

      - name: Generate Unit Test Coverage Report
        run: opam exec -- bisect-ppx-report html -o ./doc/public/static/coverage/unit

      - name: Generate Integration Test Coverage Report
        run: opam exec -- bisect-ppx-report html -o ./doc/public/static/coverage/integration

      - name: Deploy Static Site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          public_dir: ./doc/public

  # Create a tagged release
  create-tagged-release:
    name: Create Tagged Release ${{ github.ref }}
    if: startsWith(github.ref, 'v')
    needs:
      - build-and-test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          relase_tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: _build/install/default/bin/nile
          asset_name: nile
          asset_content_type: application/octet-stream
